[project]
name = "db-data-pusher"
version = "0.1.0"
description = "Получение данных из таблицы PostgreSQL и отправка их в PushGateway."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary>=2.9.9",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0"
]
